package dev.paintcraft.client.gui.widget;

import com.mojang.blaze3d.platform.NativeImage;
import dev.paintcraft.client.color.BlockColorCache;
import dev.paintcraft.client.color.OkHsl;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.narration.NarrationElementOutput;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.function.IntConsumer;

/**
 * A 2D color picker square that plots block-texture colors in OkHSL space
 * with hard Voronoi fill. Two modes:
 * - Hard: real block-texture seeds only, hard Voronoi cells
 * - Soft: real seeds + synthesized bridge seeds in sparse regions, still hard Voronoi cells
 *
 * Bridge seeds are generated by sampling a grid across the H/L space and creating
 * intermediate colors (lerped from the 2 nearest real seeds) wherever a gap is detected.
 *
 * X axis = hue (0°–360°), Y axis = lightness (1 at top, 0 at bottom).
 */
public class ColorSquareWidget extends AbstractWidget {

    private static final int TEX_W = 128;
    private static final int TEX_H = 128;

    // Bridge seed generation parameters
    private static final int NEIGHBOR_K = 5;        // nearest neighbors per seed to form pairs
    private static final float STEP_SIZE = 0.04f;   // normalized distance between bridge seeds along an edge

    private final IntConsumer onColorPicked;
    private final DynamicTexture texture;
    private final ResourceLocation textureLoc;

    // Real seeds from block textures
    private final List<SeedColor> seeds = new ArrayList<>();
    // Synthetic bridge seeds generated in sparse regions
    private final List<SeedColor> bridgeSeeds = new ArrayList<>();

    // Mode toggle: true = soft (real + bridge seeds), false = hard (real seeds only)
    private boolean soft = true;

    public ColorSquareWidget(int x, int y, int width, int height, IntConsumer onColorPicked) {
        super(x, y, width, height, Component.literal("Color Picker"));
        this.onColorPicked = onColorPicked;

        NativeImage image = new NativeImage(TEX_W, TEX_H, true);
        fillSolid(image, 0xFF1A1A1A);
        this.texture = new DynamicTexture(image);
        this.textureLoc = Minecraft.getInstance().getTextureManager()
            .register("paintcraft_colorpicker", this.texture);
    }

    public boolean isSoft() { return soft; }

    public void setSoft(boolean soft) {
        if (this.soft != soft) {
            this.soft = soft;
            if (!seeds.isEmpty()) repaint();
        }
    }

    public void toggleMode() {
        setSoft(!soft);
    }

    /**
     * Rebuild seeds from the current block set, generate bridge seeds, and repaint.
     */
    public void rebuild(List<Block> blocks) {
        seeds.clear();
        bridgeSeeds.clear();

        Set<Integer> seen = new HashSet<>();
        for (Block block : blocks) {
            int[] colors = BlockColorCache.getColors(block);
            for (int c : colors) {
                if (seen.add(c)) {
                    OkHsl.HueLightness hl = OkHsl.fromArgb(c);
                    seeds.add(new SeedColor(hl.hue(), hl.lightness(), c,
                        linearR(c), linearG(c), linearB(c)));
                }
            }
        }

        if (seeds.size() >= 2) {
            generateBridgeSeeds();
        }

        repaint();
    }

    /**
     * Generate synthetic bridge seeds along edges between neighboring real seeds.
     * For each real seed, finds its K nearest neighbors. For each unique pair that
     * is farther apart than STEP_SIZE, inserts evenly-spaced bridge seeds along
     * the line connecting them. Colors are linear RGB lerps at each position.
     */
    private void generateBridgeSeeds() {
        int n = seeds.size();
        // Track which pairs we've already processed (avoid duplicates)
        Set<Long> processedPairs = new HashSet<>();

        for (int i = 0; i < n; i++) {
            SeedColor a = seeds.get(i);

            // Find K nearest neighbors of seed i
            float[] nearestDists = new float[NEIGHBOR_K];
            int[] nearestIdx = new int[NEIGHBOR_K];
            for (int k = 0; k < NEIGHBOR_K; k++) nearestDists[k] = Float.MAX_VALUE;

            for (int j = 0; j < n; j++) {
                if (j == i) continue;
                float d = dist2(a.hue, a.lightness, seeds.get(j));
                // Insert into sorted top-K
                if (d < nearestDists[NEIGHBOR_K - 1]) {
                    int pos = NEIGHBOR_K - 1;
                    while (pos > 0 && d < nearestDists[pos - 1]) {
                        nearestDists[pos] = nearestDists[pos - 1];
                        nearestIdx[pos] = nearestIdx[pos - 1];
                        pos--;
                    }
                    nearestDists[pos] = d;
                    nearestIdx[pos] = j;
                }
            }

            // For each neighbor pair (i, j), generate bridges along the edge
            for (int ki = 0; ki < NEIGHBOR_K; ki++) {
                if (nearestDists[ki] >= Float.MAX_VALUE) break;
                int j = nearestIdx[ki];

                // Deduplicate: use canonical ordering (smaller index first)
                long pairKey = Math.min(i, j) * (long) n + Math.max(i, j);
                if (!processedPairs.add(pairKey)) continue;

                SeedColor b = seeds.get(j);
                float dist = (float) Math.sqrt(nearestDists[ki]);

                // How many bridge seeds to insert along this edge
                int steps = (int) (dist / STEP_SIZE);
                if (steps < 2) continue; // no room for bridges

                for (int s = 1; s < steps; s++) {
                    float t = s / (float) steps; // 0→1 from a to b

                    // Position: lerp in H/L space
                    float h = a.hue + (b.hue - a.hue) * t;
                    float l = a.lightness + (b.lightness - a.lightness) * t;

                    // Color: lerp in linear RGB
                    float rLin = a.linR + (b.linR - a.linR) * t;
                    float gLin = a.linG + (b.linG - a.linG) * t;
                    float bLin = a.linB + (b.linB - a.linB) * t;

                    int ri = Math.min(255, Math.max(0, (int) (linearToSrgb(rLin) * 255f + 0.5f)));
                    int gi = Math.min(255, Math.max(0, (int) (linearToSrgb(gLin) * 255f + 0.5f)));
                    int bi = Math.min(255, Math.max(0, (int) (linearToSrgb(bLin) * 255f + 0.5f)));
                    int argb = 0xFF000000 | (ri << 16) | (gi << 8) | bi;

                    bridgeSeeds.add(new SeedColor(h, l, argb, rLin, gLin, bLin));
                }
            }
        }
    }

    /**
     * Repaint the texture using hard Voronoi fill.
     * Hard mode: only real seeds. Soft mode: real + bridge seeds.
     */
    private void repaint() {
        NativeImage img = texture.getPixels();
        if (img == null) return;

        if (seeds.isEmpty()) {
            fillSolid(img, 0xFF1A1A1A);
            texture.upload();
            return;
        }

        // Determine which seeds participate in the Voronoi fill
        List<SeedColor> activeSeeds = soft
            ? combinedSeeds()
            : seeds;

        // Fill every pixel with the nearest active seed's color (hard Voronoi)
        for (int py = 0; py < TEX_H; py++) {
            float l = 1f - (py + 0.5f) / TEX_H;
            for (int px = 0; px < TEX_W; px++) {
                float h = (px + 0.5f) / TEX_W * 360f;

                SeedColor best = null;
                float bestDist = Float.MAX_VALUE;
                for (SeedColor seed : activeSeeds) {
                    float d = dist2(h, l, seed);
                    if (d < bestDist) {
                        bestDist = d;
                        best = seed;
                    }
                }

                int color = best != null ? best.argb : 0xFF1A1A1A;
                img.setPixelRGBA(px, py, argbToAbgr(color));
            }
        }

        // Draw real seed dots: 3×3 with white outline (prominent)
        for (SeedColor seed : seeds) {
            int cx = hueToPixelX(seed.hue);
            int cy = lightnessToPixelY(seed.lightness);
            for (int dy = -1; dy <= 1; dy++) {
                for (int dx = -1; dx <= 1; dx++) {
                    int px = cx + dx;
                    int py = cy + dy;
                    if (px >= 0 && px < TEX_W && py >= 0 && py < TEX_H) {
                        if (dx == 0 && dy == 0) {
                            img.setPixelRGBA(px, py, argbToAbgr(seed.argb));
                        } else {
                            img.setPixelRGBA(px, py, 0xFFFFFFFF); // white border (ABGR)
                        }
                    }
                }
            }
        }

        // Draw bridge seed dots in soft mode: 1×1, no outline (subtle)
        if (soft) {
            for (SeedColor bridge : bridgeSeeds) {
                int px = hueToPixelX(bridge.hue);
                int py = lightnessToPixelY(bridge.lightness);
                if (px >= 0 && px < TEX_W && py >= 0 && py < TEX_H) {
                    // Subtle dot at 20% alpha so it doesn't dominate
                    img.setPixelRGBA(px, py, 0x33888888); // 20% alpha gray in ABGR
                }
            }
        }

        texture.upload();
    }

    private List<SeedColor> combinedSeeds() {
        List<SeedColor> combined = new ArrayList<>(seeds.size() + bridgeSeeds.size());
        combined.addAll(seeds);
        combined.addAll(bridgeSeeds);
        return combined;
    }

    @Override
    protected void renderWidget(GuiGraphics gfx, int mouseX, int mouseY, float partialTick) {
        // Draw the texture scaled to widget bounds
        gfx.blit(textureLoc, getX(), getY(), 0, 0, width, height, width, height);

        // Border
        gfx.renderOutline(getX() - 1, getY() - 1, width + 2, height + 2, 0xFF444444);

        // Hover crosshair — snaps to nearest active seed in both modes
        if (isHovered() && !seeds.isEmpty()) {
            float h = screenXToHue(mouseX);
            float l = screenYToLightness(mouseY);
            List<SeedColor> activeSeeds = soft ? combinedSeeds() : seeds;
            SeedColor near = findNearestIn(h, l, activeSeeds);
            if (near != null) {
                int sx = getX() + (int)(hueToPixelX(near.hue) * (float) width / TEX_W);
                int sy = getY() + (int)(lightnessToPixelY(near.lightness) * (float) height / TEX_H);
                gfx.fill(sx - 4, sy, sx + 5, sy + 1, 0xFFFFFFFF);
                gfx.fill(sx, sy - 4, sx + 1, sy + 5, 0xFFFFFFFF);
            }
        }
    }

    @Override
    public void onClick(double mouseX, double mouseY) {
        if (seeds.isEmpty()) return;
        float h = screenXToHue((int) mouseX);
        float l = screenYToLightness((int) mouseY);
        List<SeedColor> activeSeeds = soft ? combinedSeeds() : seeds;
        SeedColor nearest = findNearestIn(h, l, activeSeeds);
        if (nearest != null) {
            onColorPicked.accept(nearest.argb);
        }
    }

    /** Release the DynamicTexture from TextureManager. Call from PaintScreen.removed(). */
    public void close() {
        Minecraft.getInstance().getTextureManager().release(textureLoc);
    }

    // --- Coordinate conversions ---

    private static int hueToPixelX(float hue) {
        return Math.min((int) (hue / 360f * TEX_W), TEX_W - 1);
    }

    private static int lightnessToPixelY(float lightness) {
        return Math.min((int) ((1f - lightness) * TEX_H), TEX_H - 1);
    }

    private float screenXToHue(int screenX) {
        float t = (screenX - getX()) / (float) width;
        return Math.max(0f, Math.min(360f, t * 360f));
    }

    private float screenYToLightness(int screenY) {
        float t = (screenY - getY()) / (float) height;
        return Math.max(0f, Math.min(1f, 1f - t));
    }

    // --- Distance ---

    private static float dist2(float h, float l, SeedColor seed) {
        float dh = (seed.hue - h) / 360f;
        float dl = seed.lightness - l;
        return dh * dh + dl * dl;
    }

    private static SeedColor findNearestIn(float h, float l, List<SeedColor> list) {
        SeedColor best = null;
        float bestDist = Float.MAX_VALUE;
        for (SeedColor seed : list) {
            float dist = dist2(h, l, seed);
            if (dist < bestDist) {
                bestDist = dist;
                best = seed;
            }
        }
        return best;
    }

    // --- Color space helpers ---

    private static float srgbToLinear(float c) {
        return c <= 0.04045f ? c / 12.92f : (float) Math.pow((c + 0.055f) / 1.055f, 2.4f);
    }

    private static float linearToSrgb(float c) {
        return c <= 0.0031308f ? c * 12.92f : 1.055f * (float) Math.pow(c, 1.0f / 2.4f) - 0.055f;
    }

    private static float linearR(int argb) { return srgbToLinear(((argb >> 16) & 0xFF) / 255f); }
    private static float linearG(int argb) { return srgbToLinear(((argb >> 8) & 0xFF) / 255f); }
    private static float linearB(int argb) { return srgbToLinear((argb & 0xFF) / 255f); }

    // --- Pixel format ---

    private static void fillSolid(NativeImage img, int abgr) {
        for (int y = 0; y < img.getHeight(); y++) {
            for (int x = 0; x < img.getWidth(); x++) {
                img.setPixelRGBA(x, y, abgr);
            }
        }
    }

    private static int argbToAbgr(int argb) {
        int a = argb & 0xFF000000;
        int r = (argb >> 16) & 0xFF;
        int g = argb & 0x0000FF00;
        int b = (argb & 0xFF) << 16;
        return a | b | g | r;
    }

    @Override
    protected void updateWidgetNarration(NarrationElementOutput narration) {
        defaultButtonNarrationText(narration);
    }

    private record SeedColor(float hue, float lightness, int argb,
                             float linR, float linG, float linB) {}
}
