# bricks-building-extended -- Minecraft modpack
#
# Based on Brick's Building 1.4.1 + Create ecosystem + building/construction additions
# NeoForge 1.21.1, 69 mods
#
# QUICK START:
#   nix run .#server           -- production server
#   nix run .#testServer       -- test server (auto-shutdown after tests)
#   nix build .#export         -- distributable tarball
#   nix build .#prismInstance  -- Prism Launcher instance directory
#   nix build .#mrpackExport   -- .mrpack for Modrinth Launcher
#   nix flake check            -- full VM regression test
#   nix develop                -- dev shell with packwiz + test tools
{
  description = "bricks-building-extended -- Minecraft modpack";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nix-minecraft.url = "github:Infinidoge/nix-minecraft";
  };

  outputs = { self, nixpkgs, nix-minecraft, ... }:
  let
    system = "x86_64-linux";
    pkgs = import nixpkgs {
      inherit system;
      overlays = [ nix-minecraft.overlay ];
    };
    lib = pkgs.lib;

    # ── Pack metadata ──────────────────────────────────────────
    packMeta = {
      name = "bricks-building-extended";
      mcVersion = "1.21.1";
      loader = "neoforge";
      loaderVersion = "21.1.172";
    };

    mcVersionUnderscore = builtins.replaceStrings ["."] ["_"] packMeta.mcVersion;

    # ── Server package ─────────────────────────────────────────
    serverPackages = {
      fabric   = pkgs.fabricServers."fabric-${mcVersionUnderscore}";
      forge    = pkgs.forgeServers."forge-${mcVersionUnderscore}";
      neoforge = pkgs.neoforgeServers."neoforge-${mcVersionUnderscore}";
      quilt    = pkgs.quiltServers."quilt-${mcVersionUnderscore}";
    };
    serverPackage = serverPackages.${packMeta.loader}
      or (throw "No server package for loader '${packMeta.loader}'. Check nix-minecraft.");

    # ── Mods ───────────────────────────────────────────────────
    # Generated by: mpt-gen-flake-mods resolved.json nix/mods.nix
    # Regenerate after adding/updating/removing mods.
    mods = import ./nix/mods.nix { inherit pkgs; };
    modsDir = pkgs.linkFarmFromDrvs "mods" (builtins.attrValues mods);

    # ── Test harness mod ───────────────────────────────────────
    # Pre-built JAR. Rebuild when changing MC version:
    #   mpt-gen-test-mod neoforge 1.21.1 ./test-harness-src
    #   cd test-harness-src && ./gradlew build
    #   cp build/libs/*.jar ../test-harness.jar
    testHarnessJar = ./test-harness.jar;
    hasTestHarness = builtins.pathExists testHarnessJar;

    testModsDir = pkgs.linkFarmFromDrvs "test-mods" (
      builtins.attrValues mods
      ++ lib.optional hasTestHarness testHarnessJar
    );

    # ── Configs ────────────────────────────────────────────────
    configsPath = ./configs;
    hasConfigs = builtins.pathExists configsPath;

    # ── Test definitions ───────────────────────────────────────
    testSuitePath = ./test-suite.json;
    testPlanPath = ./test-plan.toml;
    hasTestSuite = builtins.pathExists testSuitePath;
    hasTestPlan = builtins.pathExists testPlanPath;

    # ── Server properties ──────────────────────────────────────
    baseServerProperties = {
      enable-rcon = true;
      "rcon.port" = 25575;
      "rcon.password" = "testpass";
    };

    prodServerProperties = baseServerProperties // {
      server-port = 25565;
      online-mode = true;
      white-list = true;
      max-players = 20;
      difficulty = "normal";
      gamemode = "creative";
      motd = "${packMeta.name} server";
    };

    testServerProperties = baseServerProperties // {
      server-port = 25565;
      online-mode = false;
      white-list = false;
      max-players = 2;
      difficulty = "peaceful";
      gamemode = "survival";
      motd = "${packMeta.name} TEST";
    };

    # ── JVM flags ──────────────────────────────────────────────
    # 69 mods with Create ecosystem: 4-6G recommended
    jvmOpts = "-Xms3G -Xmx6G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200";

    # ── Python test tools ──────────────────────────────────────
    testTools = let
      scripts = [
        "resolve_mods" "gen_packwiz" "parse_mc_logs"
        "check_migration" "regression_test" "gen_test_mod"
        "gen_flake_mods"
      ];
    in pkgs.stdenvNoCC.mkDerivation {
      pname = "modpack-test-tools";
      version = "1.0.0";
      src = ./scripts;
      nativeBuildInputs = [ pkgs.makeWrapper ];
      installPhase = ''
        mkdir -p $out/lib/mpt $out/bin
        cp *.py $out/lib/mpt/
        ${lib.concatMapStringsSep "\n" (s: ''
          makeWrapper ${pkgs.python3}/bin/python3 $out/bin/mpt-${builtins.replaceStrings ["_"] ["-"] s} \
            --add-flags "$out/lib/mpt/${s}.py"
        '') scripts}
      '';
    };

    # ── Prism Launcher instance ────────────────────────────────
    loaderUids = {
      fabric   = { uid = "net.fabricmc.fabric-loader"; name = "Fabric Loader"; };
      quilt    = { uid = "org.quiltmc.quilt-loader";   name = "Quilt Loader"; };
      neoforge = { uid = "net.neoforged";              name = "NeoForge"; };
      forge    = { uid = "net.minecraftforge";         name = "Forge"; };
    };

    prismInstance = pkgs.runCommand "${packMeta.name}-prism" {} ''
      INST="$out/${packMeta.name}"
      mkdir -p "$INST/.minecraft/mods" "$INST/.minecraft/config"

      cat > "$INST/instance.cfg" <<EOF
      InstanceType=OneSix
      name=${packMeta.name}
      EOF

      cat > "$INST/mmc-pack.json" <<'MMCEOF'
      ${builtins.toJSON {
        formatVersion = 1;
        components = [
          { cachedName = "Minecraft"; uid = "net.minecraft"; version = packMeta.mcVersion; }
          {
            cachedName = loaderUids.${packMeta.loader}.name;
            uid = loaderUids.${packMeta.loader}.uid;
            version = packMeta.loaderVersion;
          }
        ];
      }}
      MMCEOF

      for jar in ${modsDir}/*; do
        ln -s "$jar" "$INST/.minecraft/mods/"
      done

      ${lib.optionalString hasConfigs ''
        cp -r ${configsPath}/* "$INST/.minecraft/config/"
      ''}
    '';

    # ── .mrpack export ─────────────────────────────────────────
    # Uses pre-generated mrpack-index.json with full mod file list
    mrpackIndex = builtins.fromJSON (builtins.readFile ./mrpack-index.json);

    mrpackExport = pkgs.runCommand "${packMeta.name}.mrpack" {
      nativeBuildInputs = [ pkgs.zip ];
    } ''
      WORK=$(mktemp -d)

      cat > "$WORK/modrinth.index.json" <<'MREOF'
      ${builtins.toJSON mrpackIndex}
      MREOF

      mkdir -p "$WORK/overrides/config"
      ${lib.optionalString hasConfigs ''
        cp -r ${configsPath}/* "$WORK/overrides/config/"
      ''}

      cd "$WORK" && zip -r "$out" .
    '';

    # ── Full export bundle ─────────────────────────────────────
    export = pkgs.runCommand "${packMeta.name}-export" {
      nativeBuildInputs = [ pkgs.gnutar pkgs.gzip ];
    } ''
      ROOT="$out/${packMeta.name}"
      mkdir -p "$ROOT"/{mods,config,pack}

      for jar in ${modsDir}/*; do
        cp "$jar" "$ROOT/mods/"
      done

      ${lib.optionalString hasConfigs ''
        cp -r ${configsPath}/* "$ROOT/config/"
      ''}

      if [ -d ${./pack} ]; then
        cp -r ${./pack}/* "$ROOT/pack/"
      fi

      ${lib.optionalString hasTestSuite ''cp ${testSuitePath} "$ROOT/test-suite.json"''}
      ${lib.optionalString hasTestPlan ''cp ${testPlanPath} "$ROOT/test-plan.toml"''}

      cat > "$ROOT/run-server.sh" <<'RUNEOF'
      #!/usr/bin/env bash
      set -euo pipefail
      DIR="$(cd "$(dirname "$0")" && pwd)"
      echo "eula=true" > "$DIR/eula.txt"
      exec java ${jvmOpts} -jar server.jar --nogui "$@"
      RUNEOF
      chmod +x "$ROOT/run-server.sh"

      cat > "$ROOT/README.md" <<'READMEEOF'
      # ${packMeta.name}

      Minecraft ${packMeta.mcVersion} + ${packMeta.loader} ${packMeta.loaderVersion}

      ## NixOS (recommended)
      ```
      nix run .#server
      ```

      ## Non-Nix
      1. Install Minecraft server ${packMeta.mcVersion} with ${packMeta.loader}
      2. Copy mods/ into your server directory
      3. Copy config/ into your server directory
      4. Run: ./run-server.sh

      ## Prism Launcher
      Build the Prism instance: `nix build .#prismInstance`
      Copy the output directory into your Prism instances folder.
      READMEEOF

      cd "$out" && tar czf "${packMeta.name}.tar.gz" "${packMeta.name}/"
    '';

  in {
    # ── Packages ───────────────────────────────────────────────
    packages.${system} = {
      server = pkgs.writeShellScriptBin "${packMeta.name}-server" ''
        set -euo pipefail
        WORKDIR="''${1:-./${packMeta.name}-data}"
        mkdir -p "$WORKDIR"
        echo "eula=true" > "$WORKDIR/eula.txt"
        rm -f "$WORKDIR/mods"
        ln -sfn ${modsDir} "$WORKDIR/mods"
        ${lib.optionalString hasConfigs ''
          mkdir -p "$WORKDIR/config"
          cp -rn ${configsPath}/* "$WORKDIR/config/" 2>/dev/null || true
        ''}
        cd "$WORKDIR"
        exec ${serverPackage}/bin/minecraft-server \
          ${jvmOpts} --nogui
      '';

      testServer = pkgs.writeShellScriptBin "${packMeta.name}-test" ''
        set -euo pipefail
        WORKDIR="''${1:-./${packMeta.name}-test-data}"
        mkdir -p "$WORKDIR"
        echo "eula=true" > "$WORKDIR/eula.txt"
        rm -f "$WORKDIR/mods"
        ln -sfn ${testModsDir} "$WORKDIR/mods"
        ${lib.optionalString hasConfigs ''
          mkdir -p "$WORKDIR/config"
          cp -rn ${configsPath}/* "$WORKDIR/config/" 2>/dev/null || true
        ''}
        ${lib.optionalString hasTestSuite ''
          cp ${testSuitePath} "$WORKDIR/test-suite.json"
        ''}
        cd "$WORKDIR"
        ${serverPackage}/bin/minecraft-server \
          ${jvmOpts} --nogui
        echo ""
        echo "=== Server exited ==="
        if [ -f "$WORKDIR/test-results.json" ]; then
          echo "Test results: $WORKDIR/test-results.json"
          ${pkgs.python3}/bin/python3 -c "
import json, sys
with open('$WORKDIR/test-results.json') as f:
    d = json.load(f)
p, f, t = d.get('passed',0), d.get('failed',0), d.get('total',0)
print(f'  {{p}}/{{t}} passed, {{f}} failed')
for r in d.get('results',[]):
    if not r.get('passed'):
        print(f'  FAIL: {{r[\"name\"]}} - {{r.get(\"message\",\"\")}}')
sys.exit(1 if f > 0 else 0)
"
        fi
      '';

      inherit testTools prismInstance mrpackExport export;
      default = self.packages.${system}.server;
    };

    # ── NixOS module ───────────────────────────────────────────
    nixosModules.default = { config, lib, ... }: {
      imports = [ nix-minecraft.nixosModules.minecraft-servers ];

      services.minecraft-servers = {
        enable = true;
        eula = true;

        servers.${packMeta.name} = {
          enable = true;
          package = serverPackage;
          jvmOpts = jvmOpts;

          symlinks = {
            "mods" = modsDir;
          } // lib.optionalAttrs hasConfigs {
            "config" = configsPath;
          };

          serverProperties = prodServerProperties;
        };
      };
    };

    # ── VM integration test ────────────────────────────────────
    checks.${system}.modpack-test = pkgs.nixosTest {
      name = "${packMeta.name}-integration";

      nodes.server = { config, lib, ... }: {
        imports = [ nix-minecraft.nixosModules.minecraft-servers ];

        virtualisation.memorySize = 4096;
        virtualisation.cores = 2;
        virtualisation.diskSize = 4096;

        services.minecraft-servers = {
          enable = true;
          eula = true;

          servers.test = {
            enable = true;
            package = serverPackage;
            jvmOpts = jvmOpts;

            symlinks = {
              "mods" = testModsDir;
            } // lib.optionalAttrs hasConfigs {
              "config" = configsPath;
            };

            files = { }
              // lib.optionalAttrs hasTestSuite {
                "test-suite.json" = testSuitePath;
              };

            serverProperties = testServerProperties;
          };
        };
      };

      testScript = ''
        import json

        server.start()
        server.wait_for_unit("minecraft-server-test.service")

        server.wait_until_succeeds(
            "test -f /srv/minecraft/test/test-results.json",
            timeout=300,
        )

        raw = server.succeed("cat /srv/minecraft/test/test-results.json")
        data = json.loads(raw)

        total = data.get("total", 0)
        passed = data.get("passed", 0)
        failed = data.get("failed", 0)

        print(f"\n{'='*60}")
        print(f"  In-game tests: {passed}/{total} passed, {failed} failed")
        print(f"{'='*60}\n")

        if total == 0:
            raise Exception(
                "No tests executed. Check that test-suite.json is in the server "
                "directory and the test harness mod is loaded."
            )

        if failed > 0:
            for r in data.get("results", []):
                if not r.get("passed"):
                    print(f"  FAIL: {r['name']} -- {r.get('message', 'no details')}")
            raise Exception(f"{failed} in-game test(s) failed")

        print("All in-game tests passed.")
      '';
    };

    # ── Dev shell ──────────────────────────────────────────────
    devShells.${system}.default = pkgs.mkShell {
      packages = [
        pkgs.packwiz
        pkgs.python3
        pkgs.jdk21
        pkgs.gradle
        testTools
      ];

      shellHook = ''
        echo ""
        echo "  ${packMeta.name} -- Minecraft ${packMeta.mcVersion} + ${packMeta.loader}"
        echo ""
        echo "  Run:"
        echo "    nix run .#server           production server"
        echo "    nix run .#testServer       test server (auto-shutdown)"
        echo ""
        echo "  Build:"
        echo "    nix build .#export         distributable tarball"
        echo "    nix build .#prismInstance  Prism Launcher instance"
        echo "    nix build .#mrpackExport   .mrpack for Modrinth"
        echo ""
        echo "  Test:"
        echo "    nix flake check            full VM integration test"
        echo ""
        echo "  Tools: mpt-resolve-mods, mpt-gen-packwiz, mpt-parse-mc-logs,"
        echo "         mpt-check-migration, mpt-regression-test, mpt-gen-test-mod,"
        echo "         mpt-gen-flake-mods"
        echo ""
      '';
    };
  };
}
