name = "inkwell"
author = "knoc-off"
version = "0.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c85073c4ca7f6bed15a1cbac7d062f88d79376a6a3cdc4b0b2f7a491f04b7b55"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
