name = "inkwell"
author = "knoc-off"
version = "0.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76f512c8e33c3cd7cb78ca860160c5183e1c499db9cba6a26d34f22ea4f37929"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
