#!/usr/bin/env bash
#
# Regenerate nix/local-mods.nix from a published GitHub Release of the local
# mods (asset-shelf, paint-craft, structure-stash), built by
# .github/workflows/build.yml.
#
# Usage:
#   scripts/gen-local-mods-nix.sh mods-v0.1.0
#
# For each mod, fetches <mod_id>-<mod_version>.jar from the given release tag,
# computes its sha256, and writes nix/local-mods.nix with fetchurl entries
# pointing at it. Run this after tagging + pushing a release and waiting for
# CI to publish the jars.
#
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REMOTE_URL="$(git -C "$REPO" remote get-url origin)"
# git@github.com:owner/repo.git or https://github.com/owner/repo.git -> owner/repo
GH_REPO="$(echo "$REMOTE_URL" | sed -E 's#.*[:/]([^/]+/[^/]+?)(\.git)?$#\1#')"

TAG="${1:?usage: scripts/gen-local-mods-nix.sh <release-tag>}"

MODS=(asset-shelf paint-craft structure-stash)

OUT="$REPO/nix/local-mods.nix"
{
  echo "# Local mods (asset-shelf, paint-craft, structure-stash), built by CI and"
  echo "# published as GitHub Release assets (see .github/workflows/build.yml)."
  echo "#"
  echo "# Generated by scripts/gen-local-mods-nix.sh $TAG -- do not edit manually."
  echo "# Regenerate after cutting a new release:"
  echo "#   gen-nix-local-mods $TAG   (in \`nix develop\`)"
  echo
  echo "{ pkgs }:"
  echo
  echo "{"
} > "$OUT"

for m in "${MODS[@]}"; do
  props="$REPO/packages/$m/gradle.properties"
  id="$(sed -n 's/^mod_id=//p' "$props")"
  ver="$(sed -n 's/^mod_version=//p' "$props")"
  jar="${id}-${ver}.jar"
  url="https://github.com/$GH_REPO/releases/download/$TAG/$jar"

  echo ">> Prefetching $jar from $url"
  hash="$(nix store prefetch-file --json "$url" | jq -r '.hash')"

  {
    echo "  \"$id\" = {"
    echo "    jar = pkgs.fetchurl {"
    echo "      url = \"$url\";"
    echo "      hash = \"$hash\";"
    echo "      name = \"$jar\";"
    echo "    };"
    echo "  };"
  } >> "$OUT"
done

echo "}" >> "$OUT"

echo ">> Wrote $OUT"
