#!/usr/bin/env python3
"""Generate nix/mods.nix from resolved mod data.

Reads the output of resolve_mods.py and produces a Nix expression
with fetchurl derivations for each mod, suitable for importing
in the modpack flake.

Usage:
  gen_flake_mods.py <resolved.json> [output_path]

Output defaults to ./nix/mods.nix
"""

import json
import os
import sys
from pathlib import Path


def sanitize_nix_name(slug: str) -> str:
    return slug.replace(".", "-").replace("_", "-")


def generate_mods_nix(resolved: dict) -> str:
    mods = resolved.get("resolved", [])

    lines = [
        "# Auto-generated by gen_flake_mods.py -- do not edit manually.",
        f"# Source: resolved.json for {resolved.get('loader', '?')} on Minecraft {resolved.get('minecraft_version', '?')}",
        f"# {len(mods)} mods",
        "",
        "{ pkgs }:",
        "",
        "{",
    ]

    for mod in sorted(mods, key=lambda m: m["slug"]):
        name = sanitize_nix_name(mod["slug"])
        url = mod["file_url"]
        hash_fmt = mod.get("hash_format", "sha512")
        hash_val = mod.get("file_hash", "")

        # Nix fetchurl wants SRI hashes (sha256-xxx or sha512-xxx)
        # Modrinth provides raw hex hashes. We need to note this
        # for the agent: either convert to SRI or use outputHash directly.
        # For now, output the raw hash with format annotation.

        lines.append(f"  # {mod['title']}")
        if mod.get("source_url"):
            lines.append(f"  # Source: {mod['source_url']}")
        lines.append(f'  "{name}" = pkgs.fetchurl {{')
        lines.append(f'    url = "{url}";')

        if hash_val:
            # Use outputHash + outputHashAlgo for hex hashes from Modrinth
            lines.append(f'    outputHashAlgo = "{hash_fmt}";')
            lines.append(f'    outputHash = "{hash_val}";')
        else:
            # Placeholder -- agent must fill in after first fetch
            lines.append(f'    hash = ""; # FIXME: run `nix-prefetch-url {url}` to get hash')

        lines.append(f"    name = \"{mod['slug']}-{mod['version_number']}.jar\";")
        lines.append("  };")
        lines.append("")

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: gen_flake_mods.py <resolved.json> [output_path]")
        print()
        print("Generates nix/mods.nix with fetchurl derivations for each mod.")
        print("Import in flake.nix: mods = import ./nix/mods.nix { inherit pkgs; };")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        resolved = json.load(f)

    output_path = sys.argv[2] if len(sys.argv) > 2 else "nix/mods.nix"

    nix_content = generate_mods_nix(resolved)

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(nix_content)

    mod_count = len(resolved.get("resolved", []))
    print(f"Generated {output_path} with {mod_count} mod derivations")
    print(f"Import in flake.nix:")
    print(f"  mods = import ./nix/mods.nix {{ inherit pkgs; }};")


if __name__ == "__main__":
    main()
